//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRP.KlientMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Form_Odpowiedzi
    {
        public int idOdpowiedzi { get; set; }
        public string trescPytania { get; set; }
        public string odpowiedz { get; set; }
    }
}
