//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRP.KlientMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WersjaPola
    {
        public int id { get; set; }
        public Nullable<int> idWersji { get; set; }
        public string pytanie { get; set; }
        public string odpowiedz { get; set; }
    }
}
