//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRP.KlientMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(StatusMetadata))]
    public partial class Status : IStatus
    {
        public int FieldIntExample;
    }

    public class StatusMetadata
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
    }
}
